AcoesAfirmativas/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include("allauth.urls")),
    path('', include('pages.urls')),
    path('projetos/',include('projetos.urls')),
]

pages/urls.py
from django.urls import path
from projetos.views import listar_projetos_destaque
from .views import AcoesAfirmativas,SobreNos
from django.views.generic import RedirectView
app_name = "pages"

urlpatterns = [
    path("projetos/",listar_projetos_destaque, name = "projetos"),
    path('',RedirectView.as_view(url="projetos/")),
    path("acoesafirmativas/",AcoesAfirmativas.as_view(), name="acoes"),
    path("sobrenos/",SobreNos.as_view(),name="sobrenos"),
]

projetos/urls.py
from django.urls import path
from .views import Cadastrar_Projeto,projeto,Detalhes_Projeto,listar_projetos,listar_projetos_destaque,pesquisa
app_name = "projetos"

urlpatterns = [
    path("list_projetos/",listar_projetos, name="listar"),
    path("listar/",listar_projetos_destaque, name="destaques"),
    path("listar/<int:id>",Detalhes_Projeto,name="detalhes_projeto"),
    path("projeto/",projeto, name="projeto"),
    path("projeto/submit",Cadastrar_Projeto, name="cadastrar"),
    path("pesquisa/",pesquisa, name="pesquisa"),
]

projetos/models.py
from django.db.models import Q
from django.db import models
from django.urls import reverse
# Create your models here.

class ProjetoQuerySet(models.query.QuerySet):

    def ativo(self): # função para produtos disponiveis
        return self.filter(ativo = True)

    def destaque(self): # função dos produtos em destaque.
        return self.filter(destaque = True, ativo = True)

class ProjetoManager(models.Manager):

    def get_queryset(self):
        return ProjetoQuerySet(self.model, using=self.db)

    def destaque(self):
        return self.get_queryset().destaque()


class Projetos(models.Model):
    nome          = models.CharField(max_length=250,blank=False,null=False)
    tematica      = models.CharField(max_length=250,blank=False,null=False)
    objetivo      = models.CharField(max_length=500,blank=False,null=False)
    justificativa = models.TextField(max_length=2000,blank=False,null=False)
    publico_alvo  = models.CharField(max_length=250,blank=False,null=False)
    data_criacao  = models.DateTimeField(auto_now=True)
    data_atualizacao = models.DateTimeField(auto_now_add=True)
    imagem        = models.ImageField(blank=False,null=False,upload_to='static/imagens/',)
    anexo         = models.FileField(blank=False,null=False,upload_to='static/anexos/')
    ativo         = models.BooleanField(default=False)
    destaque      = models.BooleanField(default=False)
    Objects       = ProjetoManager()
    objects       = ProjetoManager()
    class Meta:
        db_table = "Projeto"
    
    def __str__(self):
        return self.nome
     
    def get_absolute_url(self):
        return reverse("projetos:detalhes_projeto",args=[self.id]) 

pages/views.py
from django.views.generic import TemplateView
from projetos.models import Projetos
from django.shortcuts import render
# Create your views here.

class HomePageView(TemplateView):    
    template_name = "base/home.html"

class AcoesAfirmativas(TemplateView):    
    template_name = "acoesafirmativas/teste.html"

class SobreNos(TemplateView):
    template_name = "sobre-nos/sobrenos.html"

projetos/views.py
from django.db.models import Q
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Projetos

# Create your views here.

# Função para listar todos projetos
def listar_projetos(request):
    projeto = Projetos.objects.all()
    return render(request,"projetos/listagem.html",{"projetos":projeto})

# Função para listar projetos em destaque
def listar_projetos_destaque(request):
    projeto = Projetos.Objects.destaque()
    return render(request,"base/base.html",{"projetos": projeto})

@login_required(login_url="/accounts/login/")
def projeto(request):
    id_projeto = request.GET.get('id_projeto')
    dados = {}
    if id_projeto:
        dados['projeto'] = Projetos.objects.get(id=id_projeto)
    return render(request,"projetos/cadastro.html",dados)

@login_required(login_url="/accounts/login/")
def Cadastrar_Projeto(request):
    if request.POST:
        nome = request.POST.get("nome")
        tematica = request.POST.get("tematica")
        objetivo = request.POST.get("objetivo")
        justificativa = request.POST.get("justificativa")
        publico_alvo = request.POST.get("publico_alvo")
        id_projeto = request.POST.get("id_projeto")
        if id_projeto:
            Projetos.objects.filter(id=id_projeto).update(nome=nome,
                                                        tematica=tematica,
                                                        objetivo=objetivo,
                                                        justificativa=justificativa,
                                                        publico_alvo=publico_alvo)   
        else:
            Projetos.objects.create(nome=nome,
                                    tematica=tematica,
                                    objetivo=objetivo,
                                    justificativa=justificativa,
                                    publico_alvo=publico_alvo)
    return redirect("/")

@login_required(login_url="/accounts/login/")
def Detalhes_Projeto(request,id=None,*args,**kwargs):
    projeto = get_object_or_404(Projetos,id = id)
    return render(request,"projetos/detalhes.html",{"projeto":projeto})

def pesquisa(request,*args,**kwargs):
        query = request.GET.get('q',None)
        if query is not None:
            lookups = (Q(nome__icontains = query) | 
                        Q(tematica__icontains = query) | 
                        Q(publico_alvo__icontains = query))
            projeto = Projetos.objects.filter(lookups)
            return render(request,"pesquisa/result_pesquisa.html",{"projetos":projeto, "query":query})

templates/acoesafirmativas/teste.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <title>Ações Afirmativas</title>
  </head>
  <body>
    <header class="header__container">
      <div class="header__content container">
        <a class="nav-links" href="/">Repositório de<br>Açoes Afirmativas</a>
  
        <nav class="nav__container" id="nav-menu">
          <ul class="nav__content">
            <li><a href="/" class="nav-links">Ações Afirmativas</a></li>
            <li><a href="/" class="nav-links">Projetos</a></li>
            <li><a href="/" class="nav-links">Sobre-nós</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-links" href="{% url 'account_logout' %}">Sair</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-links" href="{% url 'account_login' %}">Entrar</a></li>
            <li class="nav-item"><a class="nav-links" href="{% url 'account_signup' %}">Cadastro</a></li>
            {% endif %}
          </ul>
        </nav>
        <div class="search__container" id="search-container">
          <div class="search-content">
            <div class="search__content">
              <form method="GET" action="{% url 'projetos:pesquisa' %}">
                <input
                  type="search"
                  name="q"
                  aria-label="Search" 
                  value='{{ request.GET.q }}'
                  placeholder="Pesquise Aqui"
                />
              </form>
            </div>
          </div>
        </div>
    </header>

    <main>
      <center>
      <section class="container" id="home">
        <div class="home__content container">
          <div class="home__title__container">
            <h1 class="home__title">Ações Afirmativas</h1>
          </div>
          <img src="{% static 'imagens/logo_ifsc.png' %}"  alt="Persons image" />
        </div>
      </section>
    </center>

    <section class="actions__container" id="acoesafirmativas">
      <div class="actions__content container">
        <img class="bg-image bg1" src="{% static 'imagens/bg1.svg' %}" alt="" />
        <img class="bg-image bg2" src="{% static 'imagens/bg2.svg' %}"alt="" />
        <h2 class="section__title">Ações<br> Afirmativas</h2>

        <div class="actions__cards__container">
          <div class="actions__line"></div>

          <div class="cards__container">
            <img src="{% static 'imagens/ifsc.png' %}"  alt="*ifsc image" />
            <div class="dot"></div>
            <div class="card__text__container">
              <p class="acoes__description">
                Ações Afirmativas são medidas que visam o direito do cidadão a ter acesso ao emprego e à educação.
                Na contemporaneidade, essas ações buscam diminuir a desigualdade social entre as pessoas permitindo-lhes ter as 
                mesmas condições e oportunidades no meio acadêmico e profissional, independente de cor ou classe social. 
                Primordialmente no Brasil, ações afirmativas se estabelecem mediante aos mecanismos de cotas, os quais destinam-se 
                às minorias, como: negros, indígenas, cidadãos com baixa renda. Desse modo, políticas públicas voltadas às necessidades de grupos marginalizados, possibilitam a inserção 
                social desses indivíduos na sociedade.
              </p>
            </div>
          </div>
          <div class="cards__container">
            <img
              class="inverter-image"
              src="{% static 'imagens/ifsc.png' %}"
              alt="action image"
            />
            <div class="dot"></div>
            <div class="card__text__container inverter-text">
              <p class="acoes__description">
                Entretanto, no cenário contemporâneo, existem diversos projetos os quais possuem
                como objetivo proporcionar a maior equidade possível. Porém, por não possuir transparência de informações, 
                a população que poderia estar sendo beneficiada com essas iniciativas, não têm conhecimento sobre essas propostas. 
                Contudo, as ações afirmativas são martirizadas a partir do momento que a inclusão remete-se a questões étnicas,
                por conta da supervalorização do povo mestiço na sociedade Brasileira, esse fato levou a problematização das cotas serem
                restritas a certos grupos étnicos. Em vista disso, diversas pessoas questionam a utilidade dessas ações existirem, 
                fundadas em argumentações precedentes de que, por exemplo, cotas raciais não são necessárias, pois todos possuem as mesmas
                oportunidades.
              </p>
            </div>
          </div>

          <div class="cards__container">
            <img src="{% static 'imagens/ifsc.png' %}" alt="ifsc image" />
            <div class="dot"></div>
            <div class="card__text__container">
              <p class="acoes__description">
                Dessa forma, tornou-se necessário debater sobre essa problemática para o entendimento da necessidade tornar-se
                essencial, a datar dessas pessoas não terem a representatividade dentro de universidades e cargos públicos. Conforme dados divulgados 
                pelo IBGE, no ano de 2018 cerca de 18,3% dos jovens pretos e pardos haviam iniciado e concluído sua graduação, em consoante com a informação,
                no mesmo ano 36,1% dos  jovens brancos estavam iniciando e concluindo a graduação do ensino superior. Portanto, é notável que a representatividade
                dos jovens pretos e pardos nas universidades é questionável.
              </p>
            </div>
          </div>

          <div class="cards__container">
            <img
              class="inverter-image"
              src="{% static 'imagens/ifsc.png' %}"
              alt="action image"
            />
            <div class="dot"></div>
            <div class="card__text__container inverter-text">
              <p class="acoes__description">
                Desse modo, faz-se necessária a intervenção das ações afirmativas em todos
                os casos, visando a máxima democratização e compartilhamento dos projetos que representam estas ações.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <footer class="footer__container">
      <div class="footer__content container">
        <i class="ri-copyright-line"></i>
        <p class="copy">2021 devCleidison. All rights reserved.</p>
      </div>
    </footer>
    
    <script src="{% static 'js/apiConsumer.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/base/apresentação-site.html
{% load static %}

<link
      href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

<section class="container" id="home">
    <div class="home__content container">
      <div class="home__title__container">
        <h5 class="home__subtitle">Repositório de</h5>
        <h1 class="home__title">Ações Afirmativas</h1>
      <!--</div>
      <img src="./assets/img/logo_ifsc.png" alt="Persons image" />
    </div>-->
  </section>

<script src="{% static 'js/main.js' %}"></script>

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <title>Ações Afirmativas</title>
  </head>
  <body>
    <header class="header__container">
      <div class="header__content container">
        <a class="nav-links" href="#home">Repositório de<br>Açoes Afirmativas</a>
  
        <nav class="nav__container" id="nav-menu">
          <ul class="nav__content">
            <li><a href="#acoesafirmativas" class="nav-links">Ações Afirmativas</a></li>
            <li><a href="#projetos" class="nav-links">Projetos</a></li>
            <li><a href="#sobrenos" class="nav-links">Sobre-nós</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-links" href="{% url 'account_logout' %}">Sair</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-links" href="{% url 'account_login' %}">Entrar</a></li>
            <li class="nav-item"><a class="nav-links" href="{% url 'account_signup' %}">Cadastro</a></li>
            {% endif %}
          </ul>
        </nav>
      
        <div class="search__container" id="search-container">
          <div class="search-content">
            <div class="search__content">
            <form method="GET" action="{% url 'projetos:pesquisa' %}">
              <input
                type="search"
                name="q"
                aria-label="Search" 
                value='{{ request.GET.q }}'
                placeholder="Pesquise Aqui"
              />
            </form>
            </div>
          </div>
        </div>
    </header>

    <main>
      <center>
      <section class="container" id="home">
        <div class="home__content container">
          <div class="home__title__container">
            <h5 class="home__subtitle">Repositório de</h5>
            <h1 class="home__title">Ações Afirmativas</h1>
          </div>
          <img src="{% static 'imagens/logo_ifsc.png' %}"  alt="Persons image" />
        </div>
      </section>
    </center>

      <section class="actions__container" id="acoesafirmativas">
        <div class="actions__content container">
          <img class="bg-image bg1" src="{% static 'imagens/bg1.svg' %}" alt="" />
          <img class="bg-image bg2" src="{% static 'imagens/bg2.svg' %}"alt="" />
          <h1 class="section__title">Ações<br> Afirmativas</h1>

          <div class="actions__cards__container">
            <div class="actions__line"></div>

            <div class="cards__container">
              <img src="{% static 'imagens/ifsc.png' %}"  alt="*ifsc image" />
              <div class="dot"></div>
              <div class="card__text__container">
                <h2 class="card__title"style="text-align: center;">Você sabe o que são ações afirmativas?</h2>
                <p class="card__description">
                  Todos já ouviram falar sobre ações Afirmativas, mas, muitas vezes não temos completa noção do que se trata e da sua completa importância na sociedade contemporânea. Dessa forma, Ações Afirmativas tem como objetivo: oferecer oportunidades de acesso ao emprego e à educação e consequentemente diminuir a desigualdade social.
                </p>
              </div>
            </div>
            <div class="cards__container">
              <img
                class="inverter-image"
                src="{% static 'imagens/ifsc.png' %}"
                alt="action image"
              />
              <div class="dot"></div>
              <div class="card__text__container inverter-text">
                <p class="card__description">
                  Um grande exemplo dessas ações no Brasil são as cotas que são especialmente para minorias, como: negros, indígenas, cidadãos com baixa renda. Sendo assim, esses grupos marginalizados são inseridos em nossa sociedade, conseguindo boas oportunidades.
                </p>
              </div>
            </div>

            <div class="cards__container">
              <img src="{% static 'imagens/ifsc.png' %}" alt="ifsc image" />
              <div class="dot"></div>
              <div class="card__text__container">
                <p class="card__description">
                  As cotas são um pequeno exemplo da presença de ações afirmativas em nossa sociedade, mas possui diversos outros projetos, que por não serem expostos para a população de forma prática e clara muitas vezes nem fazemos ideia de sua existência.
                </p>
              </div>
            </div>

            <div class="cards__container">
              <img
                class="inverter-image"
                src="{% static 'imagens/ifsc.png' %}"
                alt="ifsc image"
              />
              <div class="dot"></div>
              <div class="card__text__container inverter-text">
                <h2 class="card__title"style="text-align: center;">Lei de cotas</h2>
                <p class="card__description">
                  Ao contrário do que muitas pessoas pensam lei de cotas não são somente para negros.Essa ação foi criada pelo governo federal para dar oportunidades a mais para alunos de escola pública, de baixa renda, pardos, negros, indígenas e pessoas com deficiência de ingressarem em uma boa instituição de ensino, tanto para graduação quanto para o técnico. <br> <br>Para mais informações sobre leis de cotas acesse : <a href="http://portal.mec.gov.br/cotas/perguntas-frequentes.html">http://portal.mec.gov.br/cotas/perguntas-frequentes.html</a>

                </p>
              </div>
            </div>

            <div class="cards__container">
              <img src="{% static 'imagens/ifsc.png' %}" alt="ifsc image" />
              <div class="dot"></div>
              <div class="card__text__container">
                <p class="card__description">
                  Beneficiados: alunos de escola pública, de baixa renda, pardos, negros, indígenas e pessoas com deficiência
 <br><br>Criador: Nos últimos anos do mandato presidencial de Fernando Henrique Cardoso, do PSDB, teve início a implantação de cotas nas universidades públicas de todo o Brasil

                </p>
              </div>
            </div>  
          </div>
        </div>
      <a href="{% url 'pages:acoes' %}">
        <button class="more-btn" id="btn_acoes">
          <i class="ri-add-line"></i>
        </button>
      </a>
      </section>

      <section class="actx__container" id="projetos">
        <h2 class="actx__title">Projetos em Destaque</h2>
        <div class="actx__content container">
            {% for projeto in projetos %}
              <div class="projetos_destaque">
                <a href="{{ projeto.get_absolute_url }}">
                  <p class="text_projeto">{{ projeto.nome }}</p>
                </a>
              </div>
            {% endfor %}
        </div>
        <a href="{% url 'projetos:listar' %}">
          <button class="more-btn">
            <i class="ri-add-line"></i>
          </button>
        </a>
      </section>

      <section class="about__container" id="sobrenos">
        <div class="about__content container">
          <h2 class="section__title">Sobre Nós</h2>
          <div class="history__container">
            <div class="history__content">
              <div class="sobre-nos">
                <img
                id="img_sobre_nos"
                src="{% static 'imagens/ifsc.png' %}"
                alt="ifsc image"
                />
            </div>
            <p class="lead mb-5">Olá, estamos no último semestre de informática do IFSC Campus Gaspar e fizemos esse projeto com o objetivo de formar e informar os leitores sobre o que são ações afirmativas, seu papel na sociedade e quais ações temos em nosso câmpus. Desse modo, esperamos esclarecer as dúvidas e aprofundar seus conhecimentos sobre o assunto. Portanto, caso possuam alguma dúvida ou queiram conversar sobre o assunto estamos à disposição para ajudar <br>
                <br>
                Nosso grupo é composto por:<br><br>

                -Amanda Rafaela Eduardo: Responsável pela parte de documentação e conteúdo do site <br>
                -Thiago Alves dos Santos: Desenvolvimento Front-end <br>
                -Matheus Medeiros Oselame: Desenvolvimento Back-end <br>
                -Davi Deschamps: Desenvolvimento Front-end <br>
                -João Victor Pacheco: Desenvolvimento Front-end <br><br>

                IFSC Campus Gaspar · (47) 99248-2422 · <br><br><br>
                Caso tenha ocorrido algum problema, esteja com alguma dificuldade para acessar as páginas do site ou gostaria de dar alguma ideia. Favor entrar em contato com os administradores do projeto por meio do seguinte email:<br><br>


                <a href="mailto:acoesafirmativass@gmail.com">acoesafirmativass@gmail.com</a>
                </p>
               

            <div class="social-icons">
                <a class="social-icon" href="#!"><i class="fab fa-linkedin-in"></i></a>
                <a class="social-icon" href="#!"><i class="fab fa-github"></i></a>
                <a class="social-icon" href="#!"><i class="fab fa-twitter"></i></a>
                <a class="social-icon" href="#!"><i class="fab fa-facebook-f"></i></a>
            </div>
            </div>
          </div>
        </div>
      </section>
    </main>


    <footer class="footer__container">
      <div class="footer__content container">
        <i class="ri-copyright-line"></i>
        <p class="copy">2021 devCleidison. All rights reserved.</p>
      </div>
    </footer>

    <script src="{% static 'js/apiConsumer.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/base/list.html
{% load static %}
<link
      href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

<section class="pokedex__container" id="pokedex">
    <h2 class="pokedex__title">Projetos</h2>
    <div class="pokedex__content container"></div>
  </section>


  <script src="{% static 'js/main.js' %}"></script>

templates/pesquisa/result_pesquisa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <title>Ações Afirmativas</title>
  </head>
  <body>
    <header class="header__container">
      <div class="header__content container">
        <a class="nav-links" href="/">Repositório de<br>Açoes Afirmativas</a>
  
        <nav class="nav__container" id="nav-menu">
          <ul class="nav__content">
            <li><a href="#acoesafirmativas" class="nav-links">Ações Afirmativas</a></li>
            <li><a href="#projetos" class="nav-links">Projetos</a></li>
            <li><a href="#sobrenos" class="nav-links">Sobre-nós</a></li>
            {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-links" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li><a href="{% url 'account_login' %}"class="nav-links">Entrar</a></li>
                    <li class="nav-item">
                        <a class="nav-links" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
            {% endif %}
          </ul>
        </nav>
        
        <div class="search__container" id="search-container">
          <div class="search-content">
            <div class="search__content">
              <form method="GET" action="{% url 'projetos:pesquisa' %}">
                <input
                  type="search"
                  name="q"
                  aria-label="Search" 
                  value='{{ request.GET.q }}'
                  placeholder="Pesquise Aqui"
                />
              </form>
            </div>
          </div>
        </div>
    </header>

    <main>
      <center>
      <section class="container" id="home">
        <div class="home__content container">
          <div class="home__title__container">
            <h1 class="home__title">Resultado para {{ query }}</h1>
          </div>
          <img src="{% static 'imagens/logo_ifsc.png' %}"  alt="Persons image" />
        </div>
      </section>

    </center>
        {% if query %}
        {% else %}
        <form method="GET" action="{% url 'projetos:pesquisa' %}">
          <input
            type="search"
            name="q"
            aria-label="Search" 
            value='{{ request.GET.q }}'
            placeholder="Pesquise Aqui"
          />
        </form>
        </div>
        {% endif %}
        </div>

    <section class="actx__container" id="pokedex">
        <div class="actx__content container">
          {% for projeto in projetos %}
          <div class="projetos">
            <a href="{{projeto.get_absolute_url}}">
              <p class="text_projeto">{{ projeto.nome }}</p>
            </a>
          </div>
      {% endfor %}
        </div>
      </section>
  </body>
</html>

templates/projetos/cadastro.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <title>Ações Afirmativas</title>
  </head>
  <body>
    <header class="header__container">
      <div class="header__content container">
        <a class="nav-links" href="/">Repositório de<br>Açoes Afirmativas</a>
  
        <nav class="nav__container" id="nav-menu">
          <ul class="nav__content">
            <li><a href="/" class="nav-links">Ações Afirmativas</a></li>
            <li><a href="/" class="nav-links">Projetos</a></li>
            <li><a href="/" class="nav-links">Sobre-nós</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-links" href="{% url 'account_logout' %}">Sair</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-links" href="{% url 'account_login' %}">Entrar</a></li>
            <li class="nav-item"><a class="nav-links" href="{% url 'account_signup' %}">Cadastro</a></li>
            {% endif %}
          </ul>
        </nav>
        
        <div class="search__container" id="search-container">
          <div class="search-content">
            <div class="search__content">
            <form method="GET" action="{% url 'projetos:pesquisa' %}">
              <input
                type="search"
                name="q"
                aria-label="Search" 
                value='{{ request.GET.q }}'
                placeholder="Pesquise Aqui"
              />
            </form>
            </div>
          </div>
        </div>
    </header>
    
    <main>
      <center>
      <section class="container" id="home">
        <div class="home__content container">
          <div class="home__title__container">
            <h1 class="home__title">Cadastradar Seu Projeto</h1>
          </div>
          <img src="{% static 'imagens/logo_ifsc.png' %}"  alt="Persons image" />
        </div>
      </section>
    </center>

      <center>
      <div class="container_cadastro">
        <div class="content_cadastro">
          <form action="submit" method="POST" >{% csrf_token %}
            <div class="user-details">
              <div class="input-box">
                <span class="details">Nome</span>
                <input type="text" name="nome" placeholder="Digite o nome do projeto" required>
              </div>
              <div class="input-box">
                <span class="details">Tematica</span>
                <input type="text" name="tematica" placeholder="Digite a tematica do projeto" required>
              </div>
              <div class="input-box">
                <span class="details">Objetivo</span>
                <input type="text" name="objetivo" placeholder="Digite a tematica do projeto" required>
              </div>
              <div class="input-box">
                <span class="details">Publico Alvo</span>
                <input type="text" name="publico_alvo" placeholder="Diigte o publico alvo" required>
              </div>
              <div class="input-box">
                <span class="details">Anexo</span>
                <input type="file" name="anexo" required>
              </div>
              <div class="input-box">
                <span class="details">Imagem</span>
                <input type="file" name="imagem" required>
              </div>
              <div class="input-box">
                <span class="details">justificativa</span>
                <textarea name="justificativa" cols="80" rows="5" placeholder="Digite a justificativa do projeto">{{ projetos.justificativa }}</textarea>
              </div>
            
            </div>
            <div class="button">
              <input type="submit" value="Cadastradar">
            </div>
            <div class="btn-logout">
              <a href="/" style="color: white;">Cancelar</a>
            </div>
          </form>
        </div>
      </div>
    </center>
  </body>
</html>